version: '1.0'
services:
  jupyter-lab:
    build: .
    ports: 
      - "8888:8888"
    volumes:
      - ./main:/main
    deploy:
      resources:
        reservations:
          devices: 
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]